packages:
  - "packages/*"
# Wait until three days after release to install new versions of packages
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@arphi/*"
allowBuilds:
  core-js-pure: false
  dtrace-provider: false
  esbuild: false
  protobufjs: false
  re2: false
  unrs-resolver: false
# Workaround: `eslint-plugin-jsx-a11y` is not yet compatible with ESLint 10
peerDependencyRules:
  allowedVersions:
    "eslint-plugin-jsx-a11y>eslint": "10"
