packages:
  - "packages/*"
# Wait until three days after release to install new versions of packages
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@arphi/*"
onlyBuiltDependencies:
  - "esbuild"
  - "unrs-resolver"
