packages:
  - "packages/*"
# Wait until three days after release to install new versions of packages
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@arphi/*"
  # Renovate security update: renovate@43.4.4
  - renovate@43.4.4
onlyBuiltDependencies:
  - "esbuild"
  - "unrs-resolver"
